### ISSUE TITLE
NEW fan door

### ISSUE THREAD

**Issue by marcoemanuelecocco** [CapnBry/HeaterMeter#15]
![img-20150610-wa0009](https://cloud.githubusercontent.com/assets/12845292/8107195/d734379c-1047-11e5-929e-9b3f0dc80a79.jpg)

I've find a new metod to use the fan without barrel.

![img-20150610-wa0018](https://cloud.githubusercontent.com/assets/12845292/8107240/3ae6b738-1048-11e5-9d38-494af3ce5cff.jpg)
![img-20150610-wa0014](https://cloud.githubusercontent.com/assets/12845292/8107249/4f340cfe-1048-11e5-8a58-99b8ec31f4c7.jpg)
![img-20150610-wa0022](https://cloud.githubusercontent.com/assets/12845292/8107264/69917aaa-1048-11e5-8007-081462f10487.jpg)
![cattura](https://cloud.githubusercontent.com/assets/12845292/8107433/6ff3b7a4-1049-11e5-882f-66f448dec5d1.PNG)

**Comment by marcoemanuelecocco** [comment]
capsula_1.01.sldprt 
download the object and rename as above
https://cloud.githubusercontent.com/assets/12845292/8107309/ab2046cc-1048-11e5-82f5-0d0578ec82c9.jpg

capsula_1 01 stl
download the object and rename as above
https://cloud.githubusercontent.com/assets/12845292/8107395/21901918-1049-11e5-8d4b-a9d55baa481d.jpg

**Comment by CapnBry** [comment]
Looks neat but this is better posted at the user forums
http://tvwbb.com/forumdisplay.php?85-HeaterMeter-DIY-BBQ-Controller
