### ISSUE TITLE
Other SMS Provider

### ISSUE THREAD

**Issue by technofetishism** [CapnBry/HeaterMeter#36]
When selecting other SMS provider, the configuration box shows up within the email notifications section. 

This behaviour is evident in the current snapshot build.

![other provider bug](https://cloud.githubusercontent.com/assets/8284450/19232936/1dc46224-8f2a-11e6-9884-4c0d8054331a.png)

**Comment by technofetishism** [comment]
This issue also affects configuring pushbullet

**Comment by CapnBry** [comment]
I can confirm this is a bug. I've got a fix coming in the next snapshot, thank you for reporting! I'll close the issue once the fix is in git.

**Comment by CapnBry** [comment]
Should be fully resolved by 339fcb108bcba8351f94f18616b5b1df51421d98 and the new snapshot release. Thanks for your report!
