### ISSUE TITLE
Streaming url missing CORS headers

### ISSUE THREAD

**Issue by DavidPagels** [CapnBry/HeaterMeter#53]
I've started working on a Reactjs single page app that will integrate with heatermeters. I'm able to load the heatermeter history after updating my heatermeter to get the update resulting from https://github.com/CapnBry/HeaterMeter/issues/44, but am unable to get updates in a browser in realtime from /luci/lm/stream after that.

**Comment by CapnBry** [comment]
Should be fixed in the latest snapshot. Now both the /lm/hist and /lm/stream respect the linkmeter.allowcors setting and send the appropriate header.

Thanks for reporting!
