### ISSUE TITLE
Join Wifi network from the heatermeter

### ISSUE THREAD

**Issue by TristanDoherty** [CapnBry/HeaterMeter#56]
Feature Suggestion:
It would be wonderful to be able to select a wifi network and enter a password using the LCD screen and nav buttons (up/down to select from list of available networks and to select letters/numbers for the password).

**Comment by CapnBry** [comment]
Not gonna happen. Entering a wifi password using up up down down is a nightmare, and you'd have to include not just letters and numbers but all special characters as well. It's the same reason that you can't set a probe name from the on-device LCD. It was in there for a while but it took so long to enter a name and used a bunch of code space so I cut it out. It was really really really awful.

Switching between preconfigured wifi profiles from the LCD menu is sort of on the todo list though, which would be one way of achieving this. Even a new network could be joined by dropping to the default AP mode, then connecting over wifi and joining another network.
