### ISSUE TITLE
Raspberry pi Zero 2

### ISSUE THREAD

**Issue by brafster** [CapnBry/HeaterMeter#60]
I'm struggling to get my Pi Zero W 2 to boot. Is the software only compatible with the older version or should it work on the zero 2 as well?

**Comment by CapnBry** [comment]
Sorry, the software only works on the original Pi Zero W, not the newer Zero 2 (which has a completely different processor) so it won't even get past the bootloader. Even fixing the bootloader I kept getting crashes on startup so there's kernel changes needed to support it so I haven't gotten to trying to fix it further.

**Comment by brafster** [comment]
Ok great. Thanks! I specifically ordered the Zero 1, and they sent me the wrong one. Will get it swapped then. Thanks for the help.
