### ISSUE TITLE
Upgrading AVR firmware

### ISSUE THREAD

**Issue by brafster** [CapnBry/HeaterMeter#61]
Hi,

quite new to this... I bought a pre-compiled 4.2 board online. Currently it's running AVR 20140630B. Can I just install the latest version from the online repository, or does it also show incompatible versions for 4.3 for instance? Just want to make sure I don't break anything :-) The latest one listed is snapshots/trunk/heatermeter.hex

![image](https://user-images.githubusercontent.com/48287917/182541641-a079ab3d-b491-4945-a96e-507b54090e25.png)

**Comment by CapnBry** [comment]
All the 4.x hardware is compatible with the latest firmware. However, I highly recommend you upgrade the Pi firmware image before upgrading the AVR firmware, as AVR firmware assumes the Pi firmware is up to date.
https://heatermeter.com/dl/

Just use the `download .gz` link and upload it from the System -> Backup / Update Firmware page. Your wifi config should be preserved so long as the Keep Settings checkbox is checked.
![image](https://user-images.githubusercontent.com/677183/182651086-1857925b-266e-44d5-8499-a20f35920459.png)

**Comment by brafster** [comment]
Awesome! Thanks so much for the help.
