### ISSUE TITLE
Qn: thermoworks pro series basic usage

### ISSUE THREAD

**Issue by bsr203** [CapnBry/HeaterMeter#62]
Hello.

Thank you for this wonderful resource. I stumbled upon this project when looking for a way to measure & monitor my oven temp accurately. Unfortunately, to try it out, I found most of the components in the hardware list is not available at Mouser and [HeaterMeter store](https://store.heatermeter.com/) is down for me. Anyway, to begin with, I just wanted to simply read the temp using Arduino/Esp32.

I bought 2 probes  as recommended ([TX-1003X-AP](http://www.thermoworks.com/TX-1003X-AP?tw=HEATERMETER) & [TX-1001X-OP](http://www.thermoworks.com/TX-1001X-OP?tw=HEATERMETER)). Is there any place I can look to see (initial commit, tutorial) how to use these probs for basic measurements?

If not, I found a simple tutorial at https://github.com/skyeperry1/Maverick-ET-73-Meat-Probe-Arduino-Library
After learning, I guess I need to know few parameters to calculate the temp.
looking at the code in this repo, I see Steinhart-hart constants  defined [here](https://github.com/CapnBry/HeaterMeter/blob/0158e80b644e3b49cf752749625bc536e6cba5d9/arduino/heatermeter/hmcore.cpp#L112) Are these  (7.3431401e-4,2.1574370e-4,9.5156860e-8) the right value for thermoworks pro series?

I couldn't find the thermistor resistance. Can you please point to where in the code it is defined.

Thank you for your time.
bsr

**Comment by CapnBry** [comment]
Themistors are just resistors, so all you need to do to measure temperature with them is to form a voltage divider then math out the temperature using the Steinhart coefficients (yup, you've got the right values). The code that does that is here (and the next 12 lines):
https://github.com/CapnBry/HeaterMeter/blob/master/arduino/heatermeter/grillpid.cpp#L390

I use [3] to store the resistance of the other half of the voltage divider, which for HeaterMeter is set up as: 3.3V -> 10k resistor (this is the [3]) -> themistor -> GND. 

I can't help you write your own thing from scratch I'm afraid, but good luck and have fun! If you have any questions you can try asking at the [official forum group](https://tvwbb.com/forums/heatermeter-diy-bbq-controller.85/), as the Github issue tracker is not a Q&A support system.
